### ISSUE TITLE
JS files vanished in publish/ directory

### ISSUE THREAD

**Issue by lapinvert** [h5bp/ant-build-script#183]
Downloaded h5bp Mobile boilerplate Master from here : https://github.com/h5bp/mobile-boilerplate
Added ant-build-script source files into a "build" directory" into the above project.
Runned "ant build"
Getting "BUILD SUCCESSFUL"

But when checking the outputted files : publish/js/ doesn't contain "helper.js" and "main.js" anymore (nor their minified versions). 
(It does however output the JS only when using html comments to concatenate those scripts into only one.)

**Comment by roblarsen** [comment]
I never tested it and it was never designed to work with mobile-boilerplate. It might be possible to adjust it to work with the mobile-boilerplate project, but I wouldn't be available to do so.
