### ISSUE TITLE
How to use this build script outside my project?

### ISSUE THREAD

**Issue by dagoss** [h5bp/ant-build-script#186]
This project works fine if you drop it into a `build/` directory in an H5BP-based project. I'm trying to figure out how it could be used using the `Ant import` task from another directory.

For example, if I had a directory structure like this:

```
projects/
    my-project/
        build/
            build.xml <-- my project's build.xml
        src/
shared-stuff/
    h5bp-ant-build-script/
        build.xml <-- the script I want to import from this project
        tools/
```
If I import h5bp build file into my project, the paths to all the tools break.

What's the appropriate way to have these build scripts in some other location outside my project, while making as few changes to the build file as possible?

**Comment by roblarsen** [comment]
Hi, 

You need the `tools` folder and the `config` folder as well as the build.xml itself. 

Then, I think you can just edit the tasks in [project.properties](https://github.com/h5bp/ant-build-script/blob/master/config/project.properties) and it should work as long as everything maps correctly.

**Comment by dagoss** [comment]
Figured it out. There was two things that I needed to do:

1. Run ant with `ant -lib path/to/h5bp-ant/tools` to pick up Ant contrib
2. Import default.properties *in* my build file like this:

    <dirname property="imported.basedir" file="${ant.file.Boilerplate Build}"/>
    <property file="${imported.basedir}/config/default.properties"/>

It might be nice to add this to the README in the *Add the build script to your project* section.

**Comment by roblarsen** [comment]
@dagoss Happy to hear you figured it out. FWIW, the path to the tools directory can be updated in the project.properties to point wherever you need it. 

PRs always welcome for updated docs.

**Comment by dagoss** [comment]
Actually, I'm still not sure about this. I attempt to process a SCSS file and ran into this error:

> /home/dagoss/projects/h5bp-ant/build.xml:1318: /home/dagoss/projects/initializr/home/dagoss/projects/h5bp-ant/tools does not exist.

(that looks like the ${basedir}/${dir.build.tools}. See below)

Here's what my project's build.xml looks like:

```xml
<project basedir='..' default="default_target">
  <import file='../../h5bp-ant/build.xml'/>
  <dirname property="imported.basedir" file="${ant.file.Boilerplate Build}"/>
  <!-- before adding the line below, I got errors about there being no [my project]/build/tools -->
  <property name="dir.build.tools" value="${imported.basedir}/tools"/>
  <property name="build.css.scss" value="true"/>
  <property name="file.root.stylesheet" value="test.scss"/>
  <property file="${imported.basedir}/config/default.properties"/>

  <target name="default_target">
    <antcall target="build"/>
  </target>
</project>
```

**Comment by dagoss** [comment]
I got this to work with this tweak to the H5BP build.xml:

**Changed:**

```xml
<path id="JRuby">
  <fileset file="./${dir.build.tools}/jruby-complete-1.6.7.2.jar"/>
  <fileset file="./${dir.build.tools}/gem-sass.jar"/>
</path>
```

**To**

```xml
<path id="JRuby">
  <fileset file="${dir.build.tools}/jruby-complete-1.6.7.2.jar"/>
  <fileset file="${dir.build.tools}/gem-sass.jar"/>
</path>
```

I tried replace `./` with `${basedir}/`, but that didn't work. I'm seeing similar errors `compiler.jar`.

I don't like changing the H5BP build file by hand like that. Is there a better way to resolve this problem from my project's build file?

(Ant 1.9.6 on Linux)
